### PR TITLE
Made text view in the compose view autocorrect itself.

### PR DESCRIPTION
**Pull request by igashev**
Our clients requested to auto correct their messages while they are writing. I believe this is a very useful out of the box feature that should be enabled by default.

### CODE REVIEW

**Comment by Gerben-T** [comment]
@igashev i will check with our Mobile development team regarding this!

**Comment by sjongejan** [comment]
Thank you @igashev.

Great (default) feature for the library.

**Comment by igashev** [comment]
@sjongejan I am sorry but the release 3.1.4 (which states in the release notes that it contains this fix) you have created is pointing to the tag 3.1.4 which was created several days ago. So 3.1.4 does not actually contain the code from this PR. Release is just GitHub feature to represent tags in a more friendly/convenient way. As you have already merged this PR into master, you now have to tag it with 3.1.5 for example and optionally create a release.

**Comment by sjongejan** [comment]
@igashev Sorry, my bad. I fix it.

**Pull request merged**
