### PR TITLE
#95 Make possible to configure custom localization.

### LINKED ISSUE #95: Add support for new localizations.
**Describe the feature**
The SDK only supports 2 localizations for now the [nl](https://github.com/parley-messaging/ios-library/blob/master/Sources/Parley/nl.lproj/Localizable.strings) and [en](https://github.com/parley-messaging/ios-library/blob/master/Sources/Parley/en.lproj/Localizable.strings) localization. We would like to support more languages in our app. For now this is only possible with manually adding translations because it is always searching in the[ SDK bundle](https://github.com/parley-messaging/ios-library/blob/master/Sources/Parley/Extensions/StringExtension.swift#L36). 

**Screenshot**
NA

**Possible solution**
A possible solution would be to add the localization strings to the `Appearance` objects. 
There are only two kinds of places where this is not possible. 
- Views without an `Appearance` object (`MessageImageViewController`). To solve this a new `Appearance` object should be created.
- Non UI usage: Places where translations are used are `Parley`, `Message+Accessibility` and `MediaUploadNotificationErrorKind`. To solve this, the logic needs to be extracted and moved to the UI.

Is this a okay solution, or do you want separate objects for the translations?

### PR DESCRIPTION
**Pull request by mat1th**
This pr adds possibility to add new custom localization's with a `LocalizationManager` protocol. Resolves #95

### CODE REVIEW

**Review by alexkok — APPROVED** [review]
Thanks, looks good! 

We only would like to rename `L10nKey` to `ParleyLocalizationKey` -- Prefixed with `Parley` so we prevent clashes with Swift in case other developers use `LocalizationKey` already in case of implementing their own LocalizationManager.

**Comment by mat1th** [comment]
I've renamed `L10nKey` to `ParleyLocalizationKey` and added a test for it.

**Comment by alexkok** [comment]
Thanks! 👍

**Comment by alexkok** [comment]
Released in [4.1.1](https://github.com/parley-messaging/ios-library/releases/tag/4.1.1) 🚀

**Pull request merged**
